### PR TITLE
Pin image references by digest

### PR DESCRIPTION
**Pull request by ralphbean**
... and use dependabot automation to keep them updated.

### CODE REVIEW

**Comment by ralphbean** [comment]
Note, those `-source` tags you used are only for the source containers. You would really want to strip that `-source` suffix to get the image you really want for your base image.

But, that aside, I think this is probably the best and most maintainable way to go about it: 

* Choose the floating tag you want (latest and 1.20), but then also pin by digest.
* The floating tag lets automation like dependabot know what tag you want to track.
* It will send you PRs in the future with new digests as new images get published.

**Comment by savitaashture** [comment]
> Note, those -source tags you used are only for the source containers. You would really want to strip that -source suffix to get the image you really want for your base image.

> But, that aside, I think this is probably the best and most maintainable way to go about it:

> Choose the floating tag you want (latest and 1.20), but then also pin by digest.
The floating tag lets automation like dependabot know what tag you want to track.
It will send you PRs in the future with new digests as new images get published.

I see
Sure Thank you

**Comment by ralphbean** [comment]
Let's close this and just merge https://github.com/openshift-pipelines/ecosystem-images/pull/22 which includes this work.

**Pull request closed without merging**
